// German verb flashcard dataset (auto-curated).
//   group "b1b2": 200 common B1/B2 German verbs (everyday vocabulary)
//   group "c1c2": 200 advanced C1/C2 verbs that share a recognizable root with English
// Each entry: { de, en, level, group }
const WORDS = [
  // ===================== B1 / B2 (200 verbs) =====================
  { de: "abholen", en: "to pick up / collect", level: "B1", group: "b1b2" },
  { de: "abnehmen", en: "to lose weight / take off", level: "B1", group: "b1b2" },
  { de: "absagen", en: "to cancel", level: "B1", group: "b1b2" },
  { de: "abschließen", en: "to lock / conclude", level: "B2", group: "b1b2" },
  { de: "ahnen", en: "to suspect / sense", level: "B2", group: "b1b2" },
  { de: "anbieten", en: "to offer", level: "B1", group: "b1b2" },
  { de: "ändern", en: "to change", level: "B1", group: "b1b2" },
  { de: "anfangen", en: "to begin", level: "B1", group: "b1b2" },
  { de: "angeben", en: "to state / show off", level: "B2", group: "b1b2" },
  { de: "angehören", en: "to belong to", level: "B2", group: "b1b2" },
  { de: "anhalten", en: "to stop / hold", level: "B2", group: "b1b2" },
  { de: "ankommen", en: "to arrive", level: "B1", group: "b1b2" },
  { de: "annehmen", en: "to accept / assume", level: "B1", group: "b1b2" },
  { de: "anprobieren", en: "to try on", level: "B1", group: "b1b2" },
  { de: "anrufen", en: "to call (phone)", level: "B1", group: "b1b2" },
  { de: "anschauen", en: "to look at / watch", level: "B1", group: "b1b2" },
  { de: "ansehen", en: "to look at / view", level: "B1", group: "b1b2" },
  { de: "anstrengen", en: "to exert / strain", level: "B2", group: "b1b2" },
  { de: "antworten", en: "to answer", level: "B1", group: "b1b2" },
  { de: "anziehen", en: "to get dressed", level: "B1", group: "b1b2" },
  { de: "arbeiten", en: "to work", level: "B1", group: "b1b2" },
  { de: "atmen", en: "to breathe", level: "B2", group: "b1b2" },
  { de: "aufhören", en: "to stop / quit", level: "B1", group: "b1b2" },
  { de: "aufpassen", en: "to pay attention / watch out", level: "B1", group: "b1b2" },
  { de: "aufräumen", en: "to tidy up", level: "B1", group: "b1b2" },
  { de: "aufregen", en: "to upset / get excited", level: "B2", group: "b1b2" },
  { de: "aufstehen", en: "to get up", level: "B1", group: "b1b2" },
  { de: "aufwachen", en: "to wake up", level: "B1", group: "b1b2" },
  { de: "ausdrücken", en: "to express", level: "B2", group: "b1b2" },
  { de: "ausgeben", en: "to spend (money)", level: "B1", group: "b1b2" },
  { de: "ausmachen", en: "to turn off / arrange", level: "B1", group: "b1b2" },
  { de: "ausruhen", en: "to rest", level: "B1", group: "b1b2" },
  { de: "aussehen", en: "to look / appear", level: "B1", group: "b1b2" },
  { de: "aussteigen", en: "to get off / exit", level: "B1", group: "b1b2" },
  { de: "auswählen", en: "to select / choose", level: "B2", group: "b1b2" },
  { de: "bauen", en: "to build", level: "B1", group: "b1b2" },
  { de: "beantragen", en: "to apply for", level: "B2", group: "b1b2" },
  { de: "bedanken", en: "to thank", level: "B1", group: "b1b2" },
  { de: "bedeuten", en: "to mean", level: "B1", group: "b1b2" },
  { de: "bedienen", en: "to operate / serve", level: "B2", group: "b1b2" },
  { de: "beeilen", en: "to hurry", level: "B1", group: "b1b2" },
  { de: "befürchten", en: "to fear", level: "B2", group: "b1b2" },
  { de: "begegnen", en: "to encounter", level: "B2", group: "b1b2" },
  { de: "behalten", en: "to keep", level: "B1", group: "b1b2" },
  { de: "behandeln", en: "to treat", level: "B2", group: "b1b2" },
  { de: "beibringen", en: "to teach", level: "B2", group: "b1b2" },
  { de: "beißen", en: "to bite", level: "B2", group: "b1b2" },
  { de: "bekommen", en: "to get / receive", level: "B1", group: "b1b2" },
  { de: "benutzen", en: "to use", level: "B1", group: "b1b2" },
  { de: "beobachten", en: "to observe", level: "B2", group: "b1b2" },
  { de: "beraten", en: "to advise", level: "B2", group: "b1b2" },
  { de: "berichten", en: "to report", level: "B2", group: "b1b2" },
  { de: "beschäftigen", en: "to occupy / employ", level: "B2", group: "b1b2" },
  { de: "beschreiben", en: "to describe", level: "B1", group: "b1b2" },
  { de: "beschweren", en: "to complain", level: "B2", group: "b1b2" },
  { de: "besichtigen", en: "to view / tour", level: "B2", group: "b1b2" },
  { de: "besitzen", en: "to own", level: "B2", group: "b1b2" },
  { de: "besorgen", en: "to get / arrange", level: "B2", group: "b1b2" },
  { de: "bestellen", en: "to order", level: "B1", group: "b1b2" },
  { de: "bestimmen", en: "to determine", level: "B2", group: "b1b2" },
  { de: "besuchen", en: "to visit", level: "B1", group: "b1b2" },
  { de: "beten", en: "to pray", level: "B2", group: "b1b2" },
  { de: "betonen", en: "to emphasize", level: "B2", group: "b1b2" },
  { de: "betreten", en: "to enter", level: "B2", group: "b1b2" },
  { de: "betrügen", en: "to deceive / cheat", level: "B2", group: "b1b2" },
  { de: "beweisen", en: "to prove", level: "B2", group: "b1b2" },
  { de: "bewegen", en: "to move", level: "B2", group: "b1b2" },
  { de: "bewerben", en: "to apply", level: "B2", group: "b1b2" },
  { de: "bezahlen", en: "to pay", level: "B1", group: "b1b2" },
  { de: "beziehen", en: "to obtain / relate", level: "B2", group: "b1b2" },
  { de: "bilden", en: "to form / educate", level: "B2", group: "b1b2" },
  { de: "bitten", en: "to ask / request", level: "B1", group: "b1b2" },
  { de: "bleiben", en: "to stay", level: "B1", group: "b1b2" },
  { de: "blühen", en: "to bloom", level: "B2", group: "b1b2" },
  { de: "braten", en: "to fry / roast", level: "B2", group: "b1b2" },
  { de: "brauchen", en: "to need", level: "B1", group: "b1b2" },
  { de: "buchen", en: "to book", level: "B1", group: "b1b2" },
  { de: "dauern", en: "to last / take time", level: "B1", group: "b1b2" },
  { de: "denken", en: "to think", level: "B1", group: "b1b2" },
  { de: "drehen", en: "to turn / spin", level: "B1", group: "b1b2" },
  { de: "drücken", en: "to press / push", level: "B1", group: "b1b2" },
  { de: "duschen", en: "to shower", level: "B1", group: "b1b2" },
  { de: "einkaufen", en: "to shop", level: "B1", group: "b1b2" },
  { de: "einladen", en: "to invite", level: "B1", group: "b1b2" },
  { de: "einrichten", en: "to furnish / set up", level: "B2", group: "b1b2" },
  { de: "einschlafen", en: "to fall asleep", level: "B1", group: "b1b2" },
  { de: "einsteigen", en: "to get in / board", level: "B1", group: "b1b2" },
  { de: "empfangen", en: "to receive / greet", level: "B2", group: "b1b2" },
  { de: "empfehlen", en: "to recommend", level: "B1", group: "b1b2" },
  { de: "entdecken", en: "to discover", level: "B2", group: "b1b2" },
  { de: "entfernen", en: "to remove", level: "B2", group: "b1b2" },
  { de: "enthalten", en: "to contain", level: "B2", group: "b1b2" },
  { de: "entlassen", en: "to dismiss / lay off", level: "B2", group: "b1b2" },
  { de: "entscheiden", en: "to decide", level: "B1", group: "b1b2" },
  { de: "entschuldigen", en: "to excuse / apologize", level: "B1", group: "b1b2" },
  { de: "entspannen", en: "to relax", level: "B1", group: "b1b2" },
  { de: "entstehen", en: "to arise / emerge", level: "B2", group: "b1b2" },
  { de: "entwickeln", en: "to develop", level: "B2", group: "b1b2" },
  { de: "erfahren", en: "to find out / experience", level: "B2", group: "b1b2" },
  { de: "erfinden", en: "to invent", level: "B2", group: "b1b2" },
  { de: "erhalten", en: "to receive / maintain", level: "B2", group: "b1b2" },
  { de: "erhöhen", en: "to raise / increase", level: "B2", group: "b1b2" },
  { de: "erinnern", en: "to remember / remind", level: "B1", group: "b1b2" },
  { de: "erkälten", en: "to catch a cold", level: "B1", group: "b1b2" },
  { de: "erkennen", en: "to recognize", level: "B2", group: "b1b2" },
  { de: "erklären", en: "to explain", level: "B1", group: "b1b2" },
  { de: "erlauben", en: "to allow", level: "B1", group: "b1b2" },
  { de: "erledigen", en: "to take care of / finish", level: "B2", group: "b1b2" },
  { de: "ermöglichen", en: "to make possible", level: "B2", group: "b1b2" },
  { de: "erreichen", en: "to reach / achieve", level: "B2", group: "b1b2" },
  { de: "erschrecken", en: "to scare / be startled", level: "B2", group: "b1b2" },
  { de: "erwarten", en: "to expect", level: "B2", group: "b1b2" },
  { de: "erzählen", en: "to tell / narrate", level: "B1", group: "b1b2" },
  { de: "erziehen", en: "to raise / educate", level: "B2", group: "b1b2" },
  { de: "fehlen", en: "to be missing / lack", level: "B1", group: "b1b2" },
  { de: "feiern", en: "to celebrate", level: "B1", group: "b1b2" },
  { de: "fernsehen", en: "to watch TV", level: "B1", group: "b1b2" },
  { de: "fliehen", en: "to flee", level: "B2", group: "b1b2" },
  { de: "fließen", en: "to flow", level: "B2", group: "b1b2" },
  { de: "fordern", en: "to demand", level: "B2", group: "b1b2" },
  { de: "fördern", en: "to promote / support", level: "B2", group: "b1b2" },
  { de: "fragen", en: "to ask", level: "B1", group: "b1b2" },
  { de: "freuen", en: "to be glad / look forward", level: "B1", group: "b1b2" },
  { de: "fühlen", en: "to feel", level: "B1", group: "b1b2" },
  { de: "führen", en: "to lead / guide", level: "B1", group: "b1b2" },
  { de: "füllen", en: "to fill", level: "B1", group: "b1b2" },
  { de: "fürchten", en: "to fear", level: "B2", group: "b1b2" },
  { de: "gefallen", en: "to please / like", level: "B1", group: "b1b2" },
  { de: "gehören", en: "to belong", level: "B1", group: "b1b2" },
  { de: "gelingen", en: "to succeed", level: "B2", group: "b1b2" },
  { de: "gelten", en: "to be valid / apply", level: "B2", group: "b1b2" },
  { de: "genießen", en: "to enjoy", level: "B2", group: "b1b2" },
  { de: "geschehen", en: "to happen", level: "B2", group: "b1b2" },
  { de: "gewinnen", en: "to win", level: "B1", group: "b1b2" },
  { de: "gewöhnen", en: "to get used to", level: "B2", group: "b1b2" },
  { de: "gießen", en: "to pour / water", level: "B2", group: "b1b2" },
  { de: "glauben", en: "to believe", level: "B1", group: "b1b2" },
  { de: "gratulieren", en: "to congratulate", level: "B1", group: "b1b2" },
  { de: "greifen", en: "to grab / grip", level: "B2", group: "b1b2" },
  { de: "gründen", en: "to found / establish", level: "B2", group: "b1b2" },
  { de: "heiraten", en: "to marry", level: "B1", group: "b1b2" },
  { de: "herstellen", en: "to manufacture / produce", level: "B2", group: "b1b2" },
  { de: "hindern", en: "to hinder / prevent", level: "B2", group: "b1b2" },
  { de: "hoffen", en: "to hope", level: "B1", group: "b1b2" },
  { de: "holen", en: "to fetch / get", level: "B1", group: "b1b2" },
  { de: "kämpfen", en: "to fight", level: "B2", group: "b1b2" },
  { de: "kaufen", en: "to buy", level: "B1", group: "b1b2" },
  { de: "kennenlernen", en: "to get to know", level: "B1", group: "b1b2" },
  { de: "klingen", en: "to sound", level: "B2", group: "b1b2" },
  { de: "klingeln", en: "to ring", level: "B1", group: "b1b2" },
  { de: "klopfen", en: "to knock", level: "B2", group: "b1b2" },
  { de: "kochen", en: "to cook", level: "B1", group: "b1b2" },
  { de: "kümmern", en: "to take care of", level: "B1", group: "b1b2" },
  { de: "kündigen", en: "to quit / give notice", level: "B2", group: "b1b2" },
  { de: "lächeln", en: "to smile", level: "B1", group: "b1b2" },
  { de: "lachen", en: "to laugh", level: "B1", group: "b1b2" },
  { de: "leben", en: "to live", level: "B1", group: "b1b2" },
  { de: "legen", en: "to lay / put", level: "B1", group: "b1b2" },
  { de: "leiden", en: "to suffer", level: "B2", group: "b1b2" },
  { de: "leihen", en: "to lend / borrow", level: "B1", group: "b1b2" },
  { de: "leisten", en: "to afford / accomplish", level: "B2", group: "b1b2" },
  { de: "lernen", en: "to learn", level: "B1", group: "b1b2" },
  { de: "lösen", en: "to solve / dissolve", level: "B2", group: "b1b2" },
  { de: "lügen", en: "to lie (tell untruth)", level: "B2", group: "b1b2" },
  { de: "merken", en: "to notice / remember", level: "B1", group: "b1b2" },
  { de: "messen", en: "to measure", level: "B2", group: "b1b2" },
  { de: "mieten", en: "to rent", level: "B1", group: "b1b2" },
  { de: "mitbringen", en: "to bring along", level: "B1", group: "b1b2" },
  { de: "mitnehmen", en: "to take along", level: "B1", group: "b1b2" },
  { de: "mitteilen", en: "to inform / communicate", level: "B2", group: "b1b2" },
  { de: "nachdenken", en: "to think over / reflect", level: "B1", group: "b1b2" },
  { de: "nähen", en: "to sew", level: "B2", group: "b1b2" },
  { de: "nutzen", en: "to use / benefit", level: "B2", group: "b1b2" },
  { de: "öffnen", en: "to open", level: "B1", group: "b1b2" },
  { de: "passen", en: "to fit / suit", level: "B1", group: "b1b2" },
  { de: "passieren", en: "to happen", level: "B1", group: "b1b2" },
  { de: "pflegen", en: "to care for / nurse", level: "B2", group: "b1b2" },
  { de: "putzen", en: "to clean", level: "B1", group: "b1b2" },
  { de: "raten", en: "to advise / guess", level: "B2", group: "b1b2" },
  { de: "rauchen", en: "to smoke", level: "B1", group: "b1b2" },
  { de: "reden", en: "to talk / speak", level: "B1", group: "b1b2" },
  { de: "reichen", en: "to be enough / pass", level: "B2", group: "b1b2" },
  { de: "reinigen", en: "to clean", level: "B2", group: "b1b2" },
  { de: "reisen", en: "to travel", level: "B1", group: "b1b2" },
  { de: "rufen", en: "to call / shout", level: "B1", group: "b1b2" },
  { de: "schaffen", en: "to manage / create", level: "B1", group: "b1b2" },
  { de: "schauen", en: "to look", level: "B1", group: "b1b2" },
  { de: "scheinen", en: "to shine / seem", level: "B1", group: "b1b2" },
  { de: "schenken", en: "to give (a gift)", level: "B1", group: "b1b2" },
  { de: "schimpfen", en: "to scold / grumble", level: "B2", group: "b1b2" },
  { de: "schließen", en: "to close", level: "B1", group: "b1b2" },
  { de: "schmecken", en: "to taste", level: "B1", group: "b1b2" },
  { de: "schneiden", en: "to cut", level: "B1", group: "b1b2" },
  { de: "schweigen", en: "to be silent", level: "B2", group: "b1b2" },
  { de: "sorgen", en: "to care / provide", level: "B1", group: "b1b2" },
  { de: "spazieren", en: "to stroll", level: "B1", group: "b1b2" },
  { de: "speichern", en: "to save / store", level: "B2", group: "b1b2" },
  { de: "stattfinden", en: "to take place", level: "B2", group: "b1b2" },
  { de: "stellen", en: "to put / place", level: "B1", group: "b1b2" },
  { de: "sterben", en: "to die", level: "B1", group: "b1b2" },
  // ===================== C1 / C2 (200 shared-root verbs) =====================
  { de: "akzeptieren", en: "to accept", level: "C1", group: "c1c2" },
  { de: "addieren", en: "to add", level: "C1", group: "c1c2" },
  { de: "adoptieren", en: "to adopt", level: "C1", group: "c1c2" },
  { de: "alarmieren", en: "to alarm / alert", level: "C1", group: "c1c2" },
  { de: "analysieren", en: "to analyse", level: "C1", group: "c1c2" },
  { de: "annullieren", en: "to annul / cancel", level: "C2", group: "c1c2" },
  { de: "applaudieren", en: "to applaud", level: "C1", group: "c1c2" },
  { de: "argumentieren", en: "to argue", level: "C1", group: "c1c2" },
  { de: "arrangieren", en: "to arrange", level: "C1", group: "c1c2" },
  { de: "assoziieren", en: "to associate", level: "C2", group: "c1c2" },
  { de: "attackieren", en: "to attack", level: "C1", group: "c1c2" },
  { de: "balancieren", en: "to balance", level: "C1", group: "c1c2" },
  { de: "basieren", en: "to be based (on)", level: "C1", group: "c1c2" },
  { de: "beginnen", en: "to begin", level: "C1", group: "c1c2" },
  { de: "blockieren", en: "to block", level: "C1", group: "c1c2" },
  { de: "boykottieren", en: "to boycott", level: "C2", group: "c1c2" },
  { de: "bringen", en: "to bring", level: "C1", group: "c1c2" },
  { de: "definieren", en: "to define", level: "C1", group: "c1c2" },
  { de: "dekorieren", en: "to decorate", level: "C1", group: "c1c2" },
  { de: "delegieren", en: "to delegate", level: "C2", group: "c1c2" },
  { de: "demonstrieren", en: "to demonstrate", level: "C1", group: "c1c2" },
  { de: "deportieren", en: "to deport", level: "C2", group: "c1c2" },
  { de: "diagnostizieren", en: "to diagnose", level: "C2", group: "c1c2" },
  { de: "diktieren", en: "to dictate", level: "C1", group: "c1c2" },
  { de: "diskutieren", en: "to discuss", level: "C1", group: "c1c2" },
  { de: "dividieren", en: "to divide", level: "C1", group: "c1c2" },
  { de: "dokumentieren", en: "to document", level: "C1", group: "c1c2" },
  { de: "dominieren", en: "to dominate", level: "C1", group: "c1c2" },
  { de: "drucken", en: "to print", level: "C1", group: "c1c2" },
  { de: "existieren", en: "to exist", level: "C1", group: "c1c2" },
  { de: "experimentieren", en: "to experiment", level: "C1", group: "c1c2" },
  { de: "exportieren", en: "to export", level: "C1", group: "c1c2" },
  { de: "fallen", en: "to fall", level: "C1", group: "c1c2" },
  { de: "fangen", en: "to catch", level: "C1", group: "c1c2" },
  { de: "filtern", en: "to filter", level: "C1", group: "c1c2" },
  { de: "finanzieren", en: "to finance", level: "C1", group: "c1c2" },
  { de: "finden", en: "to find", level: "C1", group: "c1c2" },
  { de: "fokussieren", en: "to focus", level: "C2", group: "c1c2" },
  { de: "formulieren", en: "to formulate", level: "C1", group: "c1c2" },
  { de: "fotografieren", en: "to photograph", level: "C1", group: "c1c2" },
  { de: "frieren", en: "to freeze", level: "C1", group: "c1c2" },
  { de: "funktionieren", en: "to function", level: "C1", group: "c1c2" },
  { de: "garantieren", en: "to guarantee", level: "C1", group: "c1c2" },
  { de: "generieren", en: "to generate", level: "C2", group: "c1c2" },
  { de: "haben", en: "to have", level: "C1", group: "c1c2" },
  { de: "hängen", en: "to hang", level: "C1", group: "c1c2" },
  { de: "hassen", en: "to hate", level: "C1", group: "c1c2" },
  { de: "helfen", en: "to help", level: "C1", group: "c1c2" },
  { de: "identifizieren", en: "to identify", level: "C2", group: "c1c2" },
  { de: "ignorieren", en: "to ignore", level: "C1", group: "c1c2" },
  { de: "illustrieren", en: "to illustrate", level: "C2", group: "c1c2" },
  { de: "imitieren", en: "to imitate", level: "C1", group: "c1c2" },
  { de: "implementieren", en: "to implement", level: "C2", group: "c1c2" },
  { de: "importieren", en: "to import", level: "C1", group: "c1c2" },
  { de: "informieren", en: "to inform", level: "C1", group: "c1c2" },
  { de: "inspirieren", en: "to inspire", level: "C1", group: "c1c2" },
  { de: "installieren", en: "to install", level: "C1", group: "c1c2" },
  { de: "integrieren", en: "to integrate", level: "C1", group: "c1c2" },
  { de: "interessieren", en: "to interest", level: "C1", group: "c1c2" },
  { de: "interpretieren", en: "to interpret", level: "C2", group: "c1c2" },
  { de: "interviewen", en: "to interview", level: "C1", group: "c1c2" },
  { de: "investieren", en: "to invest", level: "C1", group: "c1c2" },
  { de: "isolieren", en: "to isolate", level: "C2", group: "c1c2" },
  { de: "kalkulieren", en: "to calculate", level: "C1", group: "c1c2" },
  { de: "kapitulieren", en: "to capitulate", level: "C2", group: "c1c2" },
  { de: "kommandieren", en: "to command", level: "C1", group: "c1c2" },
  { de: "kommen", en: "to come", level: "C1", group: "c1c2" },
  { de: "kommentieren", en: "to comment", level: "C1", group: "c1c2" },
  { de: "kommunizieren", en: "to communicate", level: "C1", group: "c1c2" },
  { de: "kompensieren", en: "to compensate", level: "C2", group: "c1c2" },
  { de: "komplizieren", en: "to complicate", level: "C2", group: "c1c2" },
  { de: "konfrontieren", en: "to confront", level: "C2", group: "c1c2" },
  { de: "konstruieren", en: "to construct", level: "C2", group: "c1c2" },
  { de: "kontaktieren", en: "to contact", level: "C1", group: "c1c2" },
  { de: "kontrollieren", en: "to control", level: "C1", group: "c1c2" },
  { de: "konzentrieren", en: "to concentrate", level: "C1", group: "c1c2" },
  { de: "kopieren", en: "to copy", level: "C1", group: "c1c2" },
  { de: "korrigieren", en: "to correct", level: "C1", group: "c1c2" },
  { de: "kosten", en: "to cost", level: "C1", group: "c1c2" },
  { de: "kritisieren", en: "to criticize", level: "C1", group: "c1c2" },
  { de: "landen", en: "to land", level: "C1", group: "c1c2" },
  { de: "liefern", en: "to deliver", level: "C1", group: "c1c2" },
  { de: "liegen", en: "to lie (be located)", level: "C1", group: "c1c2" },
  { de: "manipulieren", en: "to manipulate", level: "C2", group: "c1c2" },
  { de: "markieren", en: "to mark", level: "C1", group: "c1c2" },
  { de: "marschieren", en: "to march", level: "C1", group: "c1c2" },
  { de: "minimieren", en: "to minimize", level: "C2", group: "c1c2" },
  { de: "missbrauchen", en: "to misuse / abuse", level: "C2", group: "c1c2" },
  { de: "modernisieren", en: "to modernize", level: "C2", group: "c1c2" },
  { de: "motivieren", en: "to motivate", level: "C1", group: "c1c2" },
  { de: "multiplizieren", en: "to multiply", level: "C1", group: "c1c2" },
  { de: "navigieren", en: "to navigate", level: "C2", group: "c1c2" },
  { de: "nominieren", en: "to nominate", level: "C2", group: "c1c2" },
  { de: "normalisieren", en: "to normalize", level: "C2", group: "c1c2" },
  { de: "operieren", en: "to operate", level: "C1", group: "c1c2" },
  { de: "opfern", en: "to sacrifice", level: "C2", group: "c1c2" },
  { de: "organisieren", en: "to organize", level: "C1", group: "c1c2" },
  { de: "orientieren", en: "to orient", level: "C2", group: "c1c2" },
  { de: "packen", en: "to pack", level: "C1", group: "c1c2" },
  { de: "parken", en: "to park", level: "C1", group: "c1c2" },
  { de: "pflanzen", en: "to plant", level: "C1", group: "c1c2" },
  { de: "planen", en: "to plan", level: "C1", group: "c1c2" },
  { de: "plündern", en: "to plunder", level: "C2", group: "c1c2" },
  { de: "praktizieren", en: "to practise", level: "C1", group: "c1c2" },
  { de: "präsentieren", en: "to present", level: "C1", group: "c1c2" },
  { de: "produzieren", en: "to produce", level: "C1", group: "c1c2" },
  { de: "profitieren", en: "to profit", level: "C1", group: "c1c2" },
  { de: "programmieren", en: "to program", level: "C1", group: "c1c2" },
  { de: "protestieren", en: "to protest", level: "C1", group: "c1c2" },
  { de: "provozieren", en: "to provoke", level: "C2", group: "c1c2" },
  { de: "publizieren", en: "to publish", level: "C2", group: "c1c2" },
  { de: "qualifizieren", en: "to qualify", level: "C2", group: "c1c2" },
  { de: "reagieren", en: "to react", level: "C1", group: "c1c2" },
  { de: "realisieren", en: "to realize", level: "C1", group: "c1c2" },
  { de: "reduzieren", en: "to reduce", level: "C1", group: "c1c2" },
  { de: "reflektieren", en: "to reflect", level: "C2", group: "c1c2" },
  { de: "reformieren", en: "to reform", level: "C2", group: "c1c2" },
  { de: "registrieren", en: "to register", level: "C1", group: "c1c2" },
  { de: "regulieren", en: "to regulate", level: "C2", group: "c1c2" },
  { de: "reparieren", en: "to repair", level: "C1", group: "c1c2" },
  { de: "reservieren", en: "to reserve", level: "C1", group: "c1c2" },
  { de: "resignieren", en: "to resign / give up", level: "C2", group: "c1c2" },
  { de: "respektieren", en: "to respect", level: "C1", group: "c1c2" },
  { de: "restaurieren", en: "to restore", level: "C2", group: "c1c2" },
  { de: "resultieren", en: "to result", level: "C2", group: "c1c2" },
  { de: "riskieren", en: "to risk", level: "C1", group: "c1c2" },
  { de: "rollen", en: "to roll", level: "C1", group: "c1c2" },
  { de: "sammeln", en: "to gather / collect", level: "C1", group: "c1c2" },
  { de: "scannen", en: "to scan", level: "C1", group: "c1c2" },
  { de: "schockieren", en: "to shock", level: "C1", group: "c1c2" },
  { de: "senden", en: "to send", level: "C1", group: "c1c2" },
  { de: "servieren", en: "to serve", level: "C1", group: "c1c2" },
  { de: "signalisieren", en: "to signal", level: "C2", group: "c1c2" },
  { de: "singen", en: "to sing", level: "C1", group: "c1c2" },
  { de: "sinken", en: "to sink", level: "C1", group: "c1c2" },
  { de: "sitzen", en: "to sit", level: "C1", group: "c1c2" },
  { de: "sortieren", en: "to sort", level: "C1", group: "c1c2" },
  { de: "spekulieren", en: "to speculate", level: "C2", group: "c1c2" },
  { de: "spenden", en: "to donate", level: "C1", group: "c1c2" },
  { de: "spezialisieren", en: "to specialize", level: "C2", group: "c1c2" },
  { de: "springen", en: "to spring / jump", level: "C1", group: "c1c2" },
  { de: "stabilisieren", en: "to stabilize", level: "C2", group: "c1c2" },
  { de: "starten", en: "to start", level: "C1", group: "c1c2" },
  { de: "stehen", en: "to stand", level: "C1", group: "c1c2" },
  { de: "stoppen", en: "to stop", level: "C1", group: "c1c2" },
  { de: "strukturieren", en: "to structure", level: "C2", group: "c1c2" },
  { de: "studieren", en: "to study", level: "C1", group: "c1c2" },
  { de: "subtrahieren", en: "to subtract", level: "C1", group: "c1c2" },
  { de: "symbolisieren", en: "to symbolize", level: "C2", group: "c1c2" },
  { de: "telefonieren", en: "to telephone", level: "C1", group: "c1c2" },
  { de: "testen", en: "to test", level: "C1", group: "c1c2" },
  { de: "tolerieren", en: "to tolerate", level: "C2", group: "c1c2" },
  { de: "transportieren", en: "to transport", level: "C1", group: "c1c2" },
  { de: "trinken", en: "to drink", level: "C1", group: "c1c2" },
  { de: "überleben", en: "to survive", level: "C1", group: "c1c2" },
  { de: "variieren", en: "to vary", level: "C2", group: "c1c2" },
  { de: "vibrieren", en: "to vibrate", level: "C2", group: "c1c2" },
  { de: "waschen", en: "to wash", level: "C1", group: "c1c2" },
  { de: "winken", en: "to wave / wink", level: "C1", group: "c1c2" },
  { de: "wissen", en: "to know", level: "C1", group: "c1c2" },
  { de: "zelebrieren", en: "to celebrate (solemnly)", level: "C2", group: "c1c2" },
  { de: "zirkulieren", en: "to circulate", level: "C2", group: "c1c2" },
  { de: "zitieren", en: "to cite / quote", level: "C2", group: "c1c2" },
  { de: "abonnieren", en: "to subscribe", level: "C2", group: "c1c2" },
  { de: "absorbieren", en: "to absorb", level: "C2", group: "c1c2" },
  { de: "abstrahieren", en: "to abstract", level: "C2", group: "c1c2" },
  { de: "addressieren", en: "to address", level: "C1", group: "c1c2" },
  { de: "amüsieren", en: "to amuse", level: "C1", group: "c1c2" },
  { de: "annoncieren", en: "to announce / advertise", level: "C2", group: "c1c2" },
  { de: "applizieren", en: "to apply", level: "C2", group: "c1c2" },
  { de: "approbieren", en: "to approve / license", level: "C2", group: "c1c2" },
  { de: "blamieren", en: "to embarrass", level: "C1", group: "c1c2" },
  { de: "deklarieren", en: "to declare", level: "C2", group: "c1c2" },
  { de: "dekodieren", en: "to decode", level: "C2", group: "c1c2" },
  { de: "demolieren", en: "to demolish", level: "C2", group: "c1c2" },
  { de: "deprimieren", en: "to depress", level: "C2", group: "c1c2" },
  { de: "desinfizieren", en: "to disinfect", level: "C2", group: "c1c2" },
  { de: "detonieren", en: "to detonate", level: "C2", group: "c1c2" },
  { de: "differenzieren", en: "to differentiate", level: "C2", group: "c1c2" },
  { de: "digitalisieren", en: "to digitize", level: "C2", group: "c1c2" },
  { de: "distanzieren", en: "to distance", level: "C2", group: "c1c2" },
  { de: "editieren", en: "to edit", level: "C2", group: "c1c2" },
  { de: "eskalieren", en: "to escalate", level: "C2", group: "c1c2" },
  { de: "evaluieren", en: "to evaluate", level: "C2", group: "c1c2" },
  { de: "explodieren", en: "to explode", level: "C1", group: "c1c2" },
  { de: "fixieren", en: "to fix / fixate", level: "C2", group: "c1c2" },
  { de: "formatieren", en: "to format", level: "C2", group: "c1c2" },
  { de: "gravieren", en: "to engrave", level: "C2", group: "c1c2" },
  { de: "halten", en: "to hold", level: "C1", group: "c1c2" },
  { de: "harmonisieren", en: "to harmonize", level: "C2", group: "c1c2" },
  { de: "hospitalisieren", en: "to hospitalize", level: "C2", group: "c1c2" },
  { de: "infizieren", en: "to infect", level: "C2", group: "c1c2" },
  { de: "injizieren", en: "to inject", level: "C2", group: "c1c2" },
  { de: "kollabieren", en: "to collapse", level: "C2", group: "c1c2" },
  { de: "kollidieren", en: "to collide", level: "C2", group: "c1c2" },
  { de: "konservieren", en: "to conserve / preserve", level: "C2", group: "c1c2" },
  { de: "konsultieren", en: "to consult", level: "C2", group: "c1c2" },
  { de: "konsumieren", en: "to consume", level: "C1", group: "c1c2" },
  { de: "kooperieren", en: "to cooperate", level: "C2", group: "c1c2" },
  { de: "koordinieren", en: "to coordinate", level: "C2", group: "c1c2" },
];
if (typeof module !== "undefined" && module.exports) { module.exports = WORDS; }
