// High-yield German B2 verbs (300).
// Each entry: inf = infinitive, pres = 3rd person singular present,
// pret = 3rd person singular Präteritum, perfekt = Perfekt (aux + Partizip II),
// en = English meaning, ex = example sentence, exEn = example translation.
const VERBS = [
  // --- Auxiliary & modal verbs ---
  { inf: "sein", pres: "ist", pret: "war", perfekt: "ist gewesen", en: "to be", ex: "Sie ist sehr glücklich.", exEn: "She is very happy." },
  { inf: "haben", pres: "hat", pret: "hatte", perfekt: "hat gehabt", en: "to have", ex: "Wir haben viel Zeit.", exEn: "We have a lot of time." },
  { inf: "werden", pres: "wird", pret: "wurde", perfekt: "ist geworden", en: "to become", ex: "Er wird Arzt.", exEn: "He is becoming a doctor." },
  { inf: "können", pres: "kann", pret: "konnte", perfekt: "hat gekonnt", en: "to be able to, can", ex: "Ich kann gut schwimmen.", exEn: "I can swim well." },
  { inf: "müssen", pres: "muss", pret: "musste", perfekt: "hat gemusst", en: "to have to, must", ex: "Wir müssen jetzt gehen.", exEn: "We have to go now." },
  { inf: "wollen", pres: "will", pret: "wollte", perfekt: "hat gewollt", en: "to want", ex: "Sie will Medizin studieren.", exEn: "She wants to study medicine." },
  { inf: "sollen", pres: "soll", pret: "sollte", perfekt: "hat gesollt", en: "to be supposed to, should", ex: "Du sollst pünktlich sein.", exEn: "You should be punctual." },
  { inf: "dürfen", pres: "darf", pret: "durfte", perfekt: "hat gedurft", en: "to be allowed to, may", ex: "Man darf hier nicht rauchen.", exEn: "One is not allowed to smoke here." },
  { inf: "mögen", pres: "mag", pret: "mochte", perfekt: "hat gemocht", en: "to like", ex: "Ich mag klassische Musik.", exEn: "I like classical music." },
  { inf: "wissen", pres: "weiß", pret: "wusste", perfekt: "hat gewusst", en: "to know (facts)", ex: "Niemand weiß die Antwort.", exEn: "Nobody knows the answer." },

  // --- Core strong / irregular verbs ---
  { inf: "gehen", pres: "geht", pret: "ging", perfekt: "ist gegangen", en: "to go, walk", ex: "Wir gehen ins Kino.", exEn: "We're going to the cinema." },
  { inf: "kommen", pres: "kommt", pret: "kam", perfekt: "ist gekommen", en: "to come", ex: "Er kommt aus Spanien.", exEn: "He comes from Spain." },
  { inf: "sehen", pres: "sieht", pret: "sah", perfekt: "hat gesehen", en: "to see", ex: "Ich sehe den Unterschied nicht.", exEn: "I don't see the difference." },
  { inf: "geben", pres: "gibt", pret: "gab", perfekt: "hat gegeben", en: "to give", ex: "Sie gibt mir das Buch.", exEn: "She gives me the book." },
  { inf: "nehmen", pres: "nimmt", pret: "nahm", perfekt: "hat genommen", en: "to take", ex: "Er nimmt den Bus.", exEn: "He takes the bus." },
  { inf: "finden", pres: "findet", pret: "fand", perfekt: "hat gefunden", en: "to find", ex: "Ich finde meinen Schlüssel nicht.", exEn: "I can't find my key." },
  { inf: "sprechen", pres: "spricht", pret: "sprach", perfekt: "hat gesprochen", en: "to speak", ex: "Sie spricht drei Sprachen.", exEn: "She speaks three languages." },
  { inf: "lesen", pres: "liest", pret: "las", perfekt: "hat gelesen", en: "to read", ex: "Er liest jeden Abend.", exEn: "He reads every evening." },
  { inf: "essen", pres: "isst", pret: "aß", perfekt: "hat gegessen", en: "to eat", ex: "Wir essen zu Mittag.", exEn: "We're eating lunch." },
  { inf: "fahren", pres: "fährt", pret: "fuhr", perfekt: "ist gefahren", en: "to drive, go (vehicle)", ex: "Sie fährt nach Berlin.", exEn: "She's driving to Berlin." },
  { inf: "schlafen", pres: "schläft", pret: "schlief", perfekt: "hat geschlafen", en: "to sleep", ex: "Das Baby schläft ruhig.", exEn: "The baby is sleeping peacefully." },
  { inf: "tragen", pres: "trägt", pret: "trug", perfekt: "hat getragen", en: "to carry, wear", ex: "Er trägt eine schwere Tasche.", exEn: "He's carrying a heavy bag." },
  { inf: "laufen", pres: "läuft", pret: "lief", perfekt: "ist gelaufen", en: "to run, walk", ex: "Die Kinder laufen im Park.", exEn: "The children are running in the park." },
  { inf: "halten", pres: "hält", pret: "hielt", perfekt: "hat gehalten", en: "to hold, stop", ex: "Der Bus hält hier nicht.", exEn: "The bus doesn't stop here." },
  { inf: "lassen", pres: "lässt", pret: "ließ", perfekt: "hat gelassen", en: "to let, leave", ex: "Lass mich in Ruhe.", exEn: "Leave me alone." },
  { inf: "fallen", pres: "fällt", pret: "fiel", perfekt: "ist gefallen", en: "to fall", ex: "Das Blatt fällt vom Baum.", exEn: "The leaf falls from the tree." },
  { inf: "schlagen", pres: "schlägt", pret: "schlug", perfekt: "hat geschlagen", en: "to hit, beat", ex: "Sein Herz schlägt schnell.", exEn: "His heart beats fast." },
  { inf: "waschen", pres: "wäscht", pret: "wusch", perfekt: "hat gewaschen", en: "to wash", ex: "Sie wäscht die Wäsche.", exEn: "She washes the laundry." },
  { inf: "wachsen", pres: "wächst", pret: "wuchs", perfekt: "ist gewachsen", en: "to grow", ex: "Die Pflanze wächst schnell.", exEn: "The plant grows quickly." },
  { inf: "bleiben", pres: "bleibt", pret: "blieb", perfekt: "ist geblieben", en: "to stay", ex: "Wir bleiben zu Hause.", exEn: "We're staying home." },
  { inf: "schreiben", pres: "schreibt", pret: "schrieb", perfekt: "hat geschrieben", en: "to write", ex: "Sie schreibt einen Brief.", exEn: "She's writing a letter." },
  { inf: "steigen", pres: "steigt", pret: "stieg", perfekt: "ist gestiegen", en: "to climb, rise", ex: "Die Preise steigen ständig.", exEn: "Prices keep rising." },
  { inf: "scheinen", pres: "scheint", pret: "schien", perfekt: "hat geschienen", en: "to seem, shine", ex: "Die Sonne scheint heute.", exEn: "The sun is shining today." },
  { inf: "schweigen", pres: "schweigt", pret: "schwieg", perfekt: "hat geschwiegen", en: "to be silent", ex: "Er schweigt zu diesem Thema.", exEn: "He remains silent on this topic." },
  { inf: "reiten", pres: "reitet", pret: "ritt", perfekt: "ist geritten", en: "to ride (a horse)", ex: "Sie reitet jeden Samstag.", exEn: "She rides every Saturday." },
  { inf: "schneiden", pres: "schneidet", pret: "schnitt", perfekt: "hat geschnitten", en: "to cut", ex: "Er schneidet das Brot.", exEn: "He cuts the bread." },
  { inf: "streiten", pres: "streitet", pret: "stritt", perfekt: "hat gestritten", en: "to argue", ex: "Die Kinder streiten oft.", exEn: "The children often argue." },
  { inf: "greifen", pres: "greift", pret: "griff", perfekt: "hat gegriffen", en: "to grasp, grab", ex: "Er greift nach dem Glas.", exEn: "He reaches for the glass." },
  { inf: "beißen", pres: "beißt", pret: "biss", perfekt: "hat gebissen", en: "to bite", ex: "Der Hund beißt nicht.", exEn: "The dog doesn't bite." },
  { inf: "reißen", pres: "reißt", pret: "riss", perfekt: "hat gerissen", en: "to tear", ex: "Das Papier reißt leicht.", exEn: "The paper tears easily." },
  { inf: "bieten", pres: "bietet", pret: "bot", perfekt: "hat geboten", en: "to offer", ex: "Die Firma bietet gute Löhne.", exEn: "The company offers good wages." },
  { inf: "fliegen", pres: "fliegt", pret: "flog", perfekt: "ist geflogen", en: "to fly", ex: "Wir fliegen nach Rom.", exEn: "We're flying to Rome." },
  { inf: "fliehen", pres: "flieht", pret: "floh", perfekt: "ist geflohen", en: "to flee", ex: "Die Familie floh vor dem Krieg.", exEn: "The family fled from the war." },
  { inf: "frieren", pres: "friert", pret: "fror", perfekt: "hat gefroren", en: "to freeze, be cold", ex: "Ich friere sehr.", exEn: "I'm very cold." },
  { inf: "genießen", pres: "genießt", pret: "genoss", perfekt: "hat genossen", en: "to enjoy", ex: "Wir genießen den Urlaub.", exEn: "We're enjoying the vacation." },
  { inf: "gießen", pres: "gießt", pret: "goss", perfekt: "hat gegossen", en: "to pour, water", ex: "Sie gießt die Blumen.", exEn: "She waters the flowers." },
  { inf: "kriechen", pres: "kriecht", pret: "kroch", perfekt: "ist gekrochen", en: "to crawl", ex: "Das Baby kriecht auf dem Boden.", exEn: "The baby crawls on the floor." },
  { inf: "riechen", pres: "riecht", pret: "roch", perfekt: "hat gerochen", en: "to smell", ex: "Das Essen riecht gut.", exEn: "The food smells good." },
  { inf: "schießen", pres: "schießt", pret: "schoss", perfekt: "hat geschossen", en: "to shoot", ex: "Er schießt ein Tor.", exEn: "He scores a goal." },
  { inf: "schließen", pres: "schließt", pret: "schloss", perfekt: "hat geschlossen", en: "to close", ex: "Das Geschäft schließt um acht.", exEn: "The shop closes at eight." },
  { inf: "verlieren", pres: "verliert", pret: "verlor", perfekt: "hat verloren", en: "to lose", ex: "Wir verlieren die Geduld.", exEn: "We're losing patience." },
  { inf: "wiegen", pres: "wiegt", pret: "wog", perfekt: "hat gewogen", en: "to weigh", ex: "Das Paket wiegt zwei Kilo.", exEn: "The package weighs two kilos." },
  { inf: "ziehen", pres: "zieht", pret: "zog", perfekt: "ist gezogen", en: "to pull, move", ex: "Sie zieht nach Hamburg.", exEn: "She's moving to Hamburg." },
  { inf: "binden", pres: "bindet", pret: "band", perfekt: "hat gebunden", en: "to tie, bind", ex: "Er bindet seine Schuhe.", exEn: "He ties his shoes." },
  { inf: "dringen", pres: "dringt", pret: "drang", perfekt: "ist gedrungen", en: "to penetrate", ex: "Das Licht dringt durch das Fenster.", exEn: "The light penetrates through the window." },
  { inf: "gelingen", pres: "gelingt", pret: "gelang", perfekt: "ist gelungen", en: "to succeed", ex: "Der Plan gelingt uns.", exEn: "The plan succeeds for us." },
  { inf: "klingen", pres: "klingt", pret: "klang", perfekt: "hat geklungen", en: "to sound", ex: "Das klingt gut.", exEn: "That sounds good." },
  { inf: "singen", pres: "singt", pret: "sang", perfekt: "hat gesungen", en: "to sing", ex: "Sie singt im Chor.", exEn: "She sings in the choir." },
  { inf: "sinken", pres: "sinkt", pret: "sank", perfekt: "ist gesunken", en: "to sink, decrease", ex: "Die Temperatur sinkt.", exEn: "The temperature is dropping." },
  { inf: "springen", pres: "springt", pret: "sprang", perfekt: "ist gesprungen", en: "to jump", ex: "Das Kind springt vor Freude.", exEn: "The child jumps for joy." },
  { inf: "stinken", pres: "stinkt", pret: "stank", perfekt: "hat gestunken", en: "to stink", ex: "Der Müll stinkt.", exEn: "The garbage stinks." },
  { inf: "trinken", pres: "trinkt", pret: "trank", perfekt: "hat getrunken", en: "to drink", ex: "Er trinkt einen Kaffee.", exEn: "He's drinking a coffee." },
  { inf: "zwingen", pres: "zwingt", pret: "zwang", perfekt: "hat gezwungen", en: "to force", ex: "Niemand zwingt dich dazu.", exEn: "Nobody is forcing you to do that." },
  { inf: "beginnen", pres: "beginnt", pret: "begann", perfekt: "hat begonnen", en: "to begin", ex: "Der Film beginnt um sieben.", exEn: "The movie starts at seven." },
  { inf: "gewinnen", pres: "gewinnt", pret: "gewann", perfekt: "hat gewonnen", en: "to win", ex: "Unsere Mannschaft gewinnt oft.", exEn: "Our team wins often." },
  { inf: "schwimmen", pres: "schwimmt", pret: "schwamm", perfekt: "ist geschwommen", en: "to swim", ex: "Sie schwimmt jeden Morgen.", exEn: "She swims every morning." },
  { inf: "backen", pres: "bäckt", pret: "backte", perfekt: "hat gebacken", en: "to bake", ex: "Meine Oma backt einen Kuchen.", exEn: "My grandma bakes a cake." },
  { inf: "graben", pres: "gräbt", pret: "grub", perfekt: "hat gegraben", en: "to dig", ex: "Er gräbt ein Loch.", exEn: "He's digging a hole." },
  { inf: "laden", pres: "lädt", pret: "lud", perfekt: "hat geladen", en: "to load", ex: "Er lädt das Gepäck ins Auto.", exEn: "He loads the luggage into the car." },
  { inf: "schaffen", pres: "schafft", pret: "schaffte", perfekt: "hat geschafft", en: "to manage, accomplish", ex: "Ich schaffe die Prüfung.", exEn: "I will manage to pass the exam." },
  { inf: "blasen", pres: "bläst", pret: "blies", perfekt: "hat geblasen", en: "to blow", ex: "Der Wind bläst stark.", exEn: "The wind is blowing strongly." },
  { inf: "braten", pres: "brät", pret: "briet", perfekt: "hat gebraten", en: "to fry, roast", ex: "Sie brät das Fleisch.", exEn: "She fries the meat." },
  { inf: "fangen", pres: "fängt", pret: "fing", perfekt: "hat gefangen", en: "to catch", ex: "Der Hund fängt den Ball.", exEn: "The dog catches the ball." },
  { inf: "raten", pres: "rät", pret: "riet", perfekt: "hat geraten", en: "to advise, guess", ex: "Ich rate dir, früh zu gehen.", exEn: "I advise you to leave early." },
  { inf: "empfehlen", pres: "empfiehlt", pret: "empfahl", perfekt: "hat empfohlen", en: "to recommend", ex: "Der Arzt empfiehlt mehr Sport.", exEn: "The doctor recommends more exercise." },
  { inf: "brechen", pres: "bricht", pret: "brach", perfekt: "hat gebrochen", en: "to break", ex: "Er bricht sich das Bein.", exEn: "He breaks his leg." },
  { inf: "erschrecken", pres: "erschrickt", pret: "erschrak", perfekt: "ist erschrocken", en: "to be startled", ex: "Sie erschrickt vor dem Hund.", exEn: "She is startled by the dog." },
  { inf: "gelten", pres: "gilt", pret: "galt", perfekt: "hat gegolten", en: "to be valid, apply", ex: "Diese Regel gilt für alle.", exEn: "This rule applies to everyone." },
  { inf: "helfen", pres: "hilft", pret: "half", perfekt: "hat geholfen", en: "to help", ex: "Er hilft seiner Schwester.", exEn: "He helps his sister." },
  { inf: "stechen", pres: "sticht", pret: "stach", perfekt: "hat gestochen", en: "to sting, prick", ex: "Die Biene sticht ihn.", exEn: "The bee stings him." },
  { inf: "stehlen", pres: "stiehlt", pret: "stahl", perfekt: "hat gestohlen", en: "to steal", ex: "Der Dieb stiehlt das Auto.", exEn: "The thief steals the car." },
  { inf: "sterben", pres: "stirbt", pret: "starb", perfekt: "ist gestorben", en: "to die", ex: "Der alte Mann stirbt friedlich.", exEn: "The old man dies peacefully." },
  { inf: "treffen", pres: "trifft", pret: "traf", perfekt: "hat getroffen", en: "to meet, hit", ex: "Wir treffen uns morgen.", exEn: "We're meeting tomorrow." },
  { inf: "werben", pres: "wirbt", pret: "warb", perfekt: "hat geworben", en: "to advertise, recruit", ex: "Die Firma wirbt um neue Kunden.", exEn: "The company advertises for new customers." },
  { inf: "werfen", pres: "wirft", pret: "warf", perfekt: "hat geworfen", en: "to throw", ex: "Er wirft den Ball.", exEn: "He throws the ball." },
  { inf: "fressen", pres: "frisst", pret: "fraß", perfekt: "hat gefressen", en: "to eat (animals)", ex: "Die Katze frisst Fisch.", exEn: "The cat eats fish." },
  { inf: "geschehen", pres: "geschieht", pret: "geschah", perfekt: "ist geschehen", en: "to happen", ex: "Was ist geschehen?", exEn: "What happened?" },
  { inf: "messen", pres: "misst", pret: "maß", perfekt: "hat gemessen", en: "to measure", ex: "Der Arzt misst den Blutdruck.", exEn: "The doctor measures the blood pressure." },
  { inf: "treten", pres: "tritt", pret: "trat", perfekt: "hat getreten", en: "to kick, step", ex: "Er tritt gegen den Ball.", exEn: "He kicks the ball." },
  { inf: "vergessen", pres: "vergisst", pret: "vergaß", perfekt: "hat vergessen", en: "to forget", ex: "Ich vergesse nie deinen Namen.", exEn: "I never forget your name." },
  { inf: "heben", pres: "hebt", pret: "hob", perfekt: "hat gehoben", en: "to lift", ex: "Er hebt die Kiste.", exEn: "He lifts the box." },
  { inf: "betrügen", pres: "betrügt", pret: "betrog", perfekt: "hat betrogen", en: "to deceive, cheat", ex: "Er betrügt seine Partnerin nicht.", exEn: "He doesn't cheat on his partner." },
  { inf: "biegen", pres: "biegt", pret: "bog", perfekt: "ist gebogen", en: "to bend, turn", ex: "Das Auto biegt um die Ecke.", exEn: "The car turns around the corner." },
  { inf: "schieben", pres: "schiebt", pret: "schob", perfekt: "hat geschoben", en: "to push", ex: "Sie schiebt den Wagen.", exEn: "She pushes the cart." },
  { inf: "schmelzen", pres: "schmilzt", pret: "schmolz", perfekt: "ist geschmolzen", en: "to melt", ex: "Das Eis schmilzt in der Sonne.", exEn: "The ice melts in the sun." },
  { inf: "hängen", pres: "hängt", pret: "hing", perfekt: "hat gehangen", en: "to hang (be suspended)", ex: "Das Bild hängt an der Wand.", exEn: "The picture hangs on the wall." },
  { inf: "stehen", pres: "steht", pret: "stand", perfekt: "hat gestanden", en: "to stand", ex: "Er steht an der Bushaltestelle.", exEn: "He's standing at the bus stop." },
  { inf: "tun", pres: "tut", pret: "tat", perfekt: "hat getan", en: "to do", ex: "Was tust du gerade?", exEn: "What are you doing right now?" },
  { inf: "rufen", pres: "ruft", pret: "rief", perfekt: "hat gerufen", en: "to call, shout", ex: "Die Mutter ruft die Kinder.", exEn: "The mother calls the children." },
  { inf: "stoßen", pres: "stößt", pret: "stieß", perfekt: "hat gestoßen", en: "to push, bump", ex: "Er stößt die Tür auf.", exEn: "He pushes the door open." },
  { inf: "heißen", pres: "heißt", pret: "hieß", perfekt: "hat geheißen", en: "to be called", ex: "Wie heißt du?", exEn: "What's your name?" },
  { inf: "denken", pres: "denkt", pret: "dachte", perfekt: "hat gedacht", en: "to think", ex: "Ich denke oft an dich.", exEn: "I often think of you." },
  { inf: "bringen", pres: "bringt", pret: "brachte", perfekt: "hat gebracht", en: "to bring", ex: "Er bringt mir Kaffee.", exEn: "He brings me coffee." },
  { inf: "brennen", pres: "brennt", pret: "brannte", perfekt: "hat gebrannt", en: "to burn", ex: "Das Feuer brennt hell.", exEn: "The fire burns brightly." },
  { inf: "kennen", pres: "kennt", pret: "kannte", perfekt: "hat gekannt", en: "to know (people/things)", ex: "Ich kenne diese Stadt gut.", exEn: "I know this city well." },
  { inf: "nennen", pres: "nennt", pret: "nannte", perfekt: "hat genannt", en: "to name, call", ex: "Man nennt ihn den Chef.", exEn: "They call him the boss." },
  { inf: "rennen", pres: "rennt", pret: "rannte", perfekt: "ist gerannt", en: "to run, race", ex: "Die Kinder rennen zur Schule.", exEn: "The children run to school." },
  { inf: "senden", pres: "sendet", pret: "sandte", perfekt: "hat gesandt", en: "to send, broadcast", ex: "Der Sender sendet die Nachrichten.", exEn: "The station broadcasts the news." },
  { inf: "wenden", pres: "wendet", pret: "wandte", perfekt: "hat gewandt", en: "to turn", ex: "Sie wendet sich an den Chef.", exEn: "She turns to the boss." },

  // --- Separable / prefixed verbs (high B2 yield) ---
  { inf: "anfangen", pres: "fängt an", pret: "fing an", perfekt: "hat angefangen", en: "to begin, start", ex: "Der Unterricht fängt um acht an.", exEn: "Class starts at eight." },
  { inf: "aufhören", pres: "hört auf", pret: "hörte auf", perfekt: "hat aufgehört", en: "to stop", ex: "Der Regen hört endlich auf.", exEn: "The rain is finally stopping." },
  { inf: "aufstehen", pres: "steht auf", pret: "stand auf", perfekt: "ist aufgestanden", en: "to get up", ex: "Ich stehe um sechs auf.", exEn: "I get up at six." },
  { inf: "ausgehen", pres: "geht aus", pret: "ging aus", perfekt: "ist ausgegangen", en: "to go out", ex: "Wir gehen heute Abend aus.", exEn: "We're going out tonight." },
  { inf: "einladen", pres: "lädt ein", pret: "lud ein", perfekt: "hat eingeladen", en: "to invite", ex: "Sie lädt mich zur Feier ein.", exEn: "She invites me to the party." },
  { inf: "vorschlagen", pres: "schlägt vor", pret: "schlug vor", perfekt: "hat vorgeschlagen", en: "to suggest", ex: "Er schlägt einen anderen Termin vor.", exEn: "He suggests another appointment." },
  { inf: "vorstellen", pres: "stellt vor", pret: "stellte vor", perfekt: "hat vorgestellt", en: "to introduce, imagine", ex: "Ich stelle dir meinen Freund vor.", exEn: "I'm introducing you to my friend." },
  { inf: "teilnehmen", pres: "nimmt teil", pret: "nahm teil", perfekt: "hat teilgenommen", en: "to participate", ex: "Sie nimmt an dem Kurs teil.", exEn: "She participates in the course." },
  { inf: "zunehmen", pres: "nimmt zu", pret: "nahm zu", perfekt: "hat zugenommen", en: "to increase, gain weight", ex: "Die Kosten nehmen zu.", exEn: "The costs are increasing." },
  { inf: "abnehmen", pres: "nimmt ab", pret: "nahm ab", perfekt: "hat abgenommen", en: "to decrease, lose weight", ex: "Er hat fünf Kilo abgenommen.", exEn: "He lost five kilos." },
  { inf: "entstehen", pres: "entsteht", pret: "entstand", perfekt: "ist entstanden", en: "to arise, originate", ex: "Ein neues Problem entsteht.", exEn: "A new problem arises." },
  { inf: "bestehen", pres: "besteht", pret: "bestand", perfekt: "hat bestanden", en: "to pass (exam), consist of, exist", ex: "Sie besteht die Prüfung.", exEn: "She passes the exam." },
  { inf: "verstehen", pres: "versteht", pret: "verstand", perfekt: "hat verstanden", en: "to understand", ex: "Ich verstehe die Frage nicht.", exEn: "I don't understand the question." },
  { inf: "umziehen", pres: "zieht um", pret: "zog um", perfekt: "ist umgezogen", en: "to move (house)", ex: "Wir ziehen nächsten Monat um.", exEn: "We're moving next month." },
  { inf: "anziehen", pres: "zieht an", pret: "zog an", perfekt: "hat angezogen", en: "to put on, dress", ex: "Sie zieht die Jacke an.", exEn: "She puts on the jacket." },
  { inf: "ausziehen", pres: "zieht aus", pret: "zog aus", perfekt: "hat ausgezogen", en: "to take off, move out", ex: "Er zieht die Schuhe aus.", exEn: "He takes off his shoes." },
  { inf: "mitbringen", pres: "bringt mit", pret: "brachte mit", perfekt: "hat mitgebracht", en: "to bring along", ex: "Bring bitte einen Salat mit.", exEn: "Please bring a salad along." },
  { inf: "mitnehmen", pres: "nimmt mit", pret: "nahm mit", perfekt: "hat mitgenommen", en: "to take along", ex: "Nimm einen Schirm mit.", exEn: "Take an umbrella with you." },
  { inf: "wegwerfen", pres: "wirft weg", pret: "warf weg", perfekt: "hat weggeworfen", en: "to throw away", ex: "Wirf das nicht weg!", exEn: "Don't throw that away!" },
  { inf: "zurückkommen", pres: "kommt zurück", pret: "kam zurück", perfekt: "ist zurückgekommen", en: "to come back", ex: "Er kommt bald zurück.", exEn: "He'll be back soon." },
  { inf: "zurückgeben", pres: "gibt zurück", pret: "gab zurück", perfekt: "hat zurückgegeben", en: "to give back", ex: "Sie gibt mir das Buch zurück.", exEn: "She gives me the book back." },
  { inf: "unterschreiben", pres: "unterschreibt", pret: "unterschrieb", perfekt: "hat unterschrieben", en: "to sign", ex: "Bitte unterschreiben Sie hier.", exEn: "Please sign here." },
  { inf: "vorbereiten", pres: "bereitet vor", pret: "bereitete vor", perfekt: "hat vorbereitet", en: "to prepare", ex: "Ich bereite das Essen vor.", exEn: "I'm preparing the meal." },
  { inf: "durchführen", pres: "führt durch", pret: "führte durch", perfekt: "hat durchgeführt", en: "to carry out", ex: "Die Firma führt eine Studie durch.", exEn: "The company carries out a study." },
  { inf: "stattfinden", pres: "findet statt", pret: "fand statt", perfekt: "hat stattgefunden", en: "to take place", ex: "Die Konferenz findet morgen statt.", exEn: "The conference takes place tomorrow." },
  { inf: "ankommen", pres: "kommt an", pret: "kam an", perfekt: "ist angekommen", en: "to arrive", ex: "Der Zug kommt pünktlich an.", exEn: "The train arrives on time." },
  { inf: "abfahren", pres: "fährt ab", pret: "fuhr ab", perfekt: "ist abgefahren", en: "to depart", ex: "Der Bus fährt um neun ab.", exEn: "The bus departs at nine." },
  { inf: "feststellen", pres: "stellt fest", pret: "stellte fest", perfekt: "hat festgestellt", en: "to determine, notice", ex: "Ich stelle einen Fehler fest.", exEn: "I notice a mistake." },
  { inf: "festhalten", pres: "hält fest", pret: "hielt fest", perfekt: "hat festgehalten", en: "to hold on to", ex: "Halt dich gut fest!", exEn: "Hold on tight!" },
  { inf: "loslassen", pres: "lässt los", pret: "ließ los", perfekt: "hat losgelassen", en: "to let go", ex: "Lass meine Hand los!", exEn: "Let go of my hand!" },
  { inf: "zulassen", pres: "lässt zu", pret: "ließ zu", perfekt: "hat zugelassen", en: "to allow, permit", ex: "Das Gesetz lässt das nicht zu.", exEn: "The law does not allow that." },
  { inf: "verlassen", pres: "verlässt", pret: "verließ", perfekt: "hat verlassen", en: "to leave (a place)", ex: "Er verlässt das Haus früh.", exEn: "He leaves the house early." },
  { inf: "entlassen", pres: "entlässt", pret: "entließ", perfekt: "hat entlassen", en: "to dismiss, fire", ex: "Die Firma entlässt zehn Mitarbeiter.", exEn: "The company lays off ten employees." },
  { inf: "überweisen", pres: "überweist", pret: "überwies", perfekt: "hat überwiesen", en: "to transfer (money)", ex: "Ich überweise das Geld heute.", exEn: "I'll transfer the money today." },
  { inf: "anrufen", pres: "ruft an", pret: "rief an", perfekt: "hat angerufen", en: "to call (phone)", ex: "Ich rufe dich später an.", exEn: "I'll call you later." },
  { inf: "aufmachen", pres: "macht auf", pret: "machte auf", perfekt: "hat aufgemacht", en: "to open", ex: "Mach bitte das Fenster auf.", exEn: "Please open the window." },
  { inf: "zumachen", pres: "macht zu", pret: "machte zu", perfekt: "hat zugemacht", en: "to close", ex: "Mach die Tür zu.", exEn: "Close the door." },
  { inf: "weggehen", pres: "geht weg", pret: "ging weg", perfekt: "ist weggegangen", en: "to go away", ex: "Er geht plötzlich weg.", exEn: "He suddenly goes away." },
  { inf: "hingehen", pres: "geht hin", pret: "ging hin", perfekt: "ist hingegangen", en: "to go there", ex: "Wo gehst du hin?", exEn: "Where are you going?" },
  { inf: "herausfinden", pres: "findet heraus", pret: "fand heraus", perfekt: "hat herausgefunden", en: "to find out", ex: "Wir finden die Wahrheit heraus.", exEn: "We find out the truth." },
  { inf: "aufwachen", pres: "wacht auf", pret: "wachte auf", perfekt: "ist aufgewacht", en: "to wake up", ex: "Ich wache früh auf.", exEn: "I wake up early." },
  { inf: "einschlafen", pres: "schläft ein", pret: "schlief ein", perfekt: "ist eingeschlafen", en: "to fall asleep", ex: "Das Kind schläft schnell ein.", exEn: "The child falls asleep quickly." },
  { inf: "aussehen", pres: "sieht aus", pret: "sah aus", perfekt: "hat ausgesehen", en: "to look, appear", ex: "Sie sieht müde aus.", exEn: "She looks tired." },
  { inf: "fernsehen", pres: "sieht fern", pret: "sah fern", perfekt: "hat ferngesehen", en: "to watch TV", ex: "Wir sehen heute Abend fern.", exEn: "We're watching TV tonight." },
  { inf: "vorlesen", pres: "liest vor", pret: "las vor", perfekt: "hat vorgelesen", en: "to read aloud", ex: "Die Mutter liest dem Kind vor.", exEn: "The mother reads to the child." },
  { inf: "mitmachen", pres: "macht mit", pret: "machte mit", perfekt: "hat mitgemacht", en: "to join in, participate", ex: "Machst du bei dem Spiel mit?", exEn: "Are you joining in the game?" },
  { inf: "zusammenarbeiten", pres: "arbeitet zusammen", pret: "arbeitete zusammen", perfekt: "hat zusammengearbeitet", en: "to work together", ex: "Wir arbeiten gut zusammen.", exEn: "We work well together." },
  { inf: "zusammenfassen", pres: "fasst zusammen", pret: "fasste zusammen", perfekt: "hat zusammengefasst", en: "to summarize", ex: "Fassen Sie den Text zusammen.", exEn: "Summarize the text." },
  { inf: "auffallen", pres: "fällt auf", pret: "fiel auf", perfekt: "ist aufgefallen", en: "to stand out, be noticed", ex: "Mir fällt ein Fehler auf.", exEn: "I notice a mistake." },
  { inf: "einfallen", pres: "fällt ein", pret: "fiel ein", perfekt: "ist eingefallen", en: "to occur to (someone)", ex: "Mir fällt nichts ein.", exEn: "Nothing occurs to me." },

  // --- er-, ver-, be-, ent- prefixed verbs ---
  { inf: "erreichen", pres: "erreicht", pret: "erreichte", perfekt: "hat erreicht", en: "to reach, achieve", ex: "Wir erreichen unser Ziel.", exEn: "We reach our goal." },
  { inf: "erklären", pres: "erklärt", pret: "erklärte", perfekt: "hat erklärt", en: "to explain", ex: "Der Lehrer erklärt die Regel.", exEn: "The teacher explains the rule." },
  { inf: "erwarten", pres: "erwartet", pret: "erwartete", perfekt: "hat erwartet", en: "to expect", ex: "Ich erwarte eine Antwort.", exEn: "I expect an answer." },
  { inf: "erhöhen", pres: "erhöht", pret: "erhöhte", perfekt: "hat erhöht", en: "to increase, raise", ex: "Die Firma erhöht die Preise.", exEn: "The company raises the prices." },
  { inf: "ermöglichen", pres: "ermöglicht", pret: "ermöglichte", perfekt: "hat ermöglicht", en: "to enable, make possible", ex: "Das Stipendium ermöglicht das Studium.", exEn: "The scholarship makes the studies possible." },
  { inf: "erwähnen", pres: "erwähnt", pret: "erwähnte", perfekt: "hat erwähnt", en: "to mention", ex: "Er erwähnt das Problem kurz.", exEn: "He briefly mentions the problem." },
  { inf: "erzählen", pres: "erzählt", pret: "erzählte", perfekt: "hat erzählt", en: "to tell, narrate", ex: "Sie erzählt eine Geschichte.", exEn: "She tells a story." },
  { inf: "erledigen", pres: "erledigt", pret: "erledigte", perfekt: "hat erledigt", en: "to take care of, handle", ex: "Ich erledige die Aufgabe heute.", exEn: "I'll handle the task today." },
  { inf: "ergänzen", pres: "ergänzt", pret: "ergänzte", perfekt: "hat ergänzt", en: "to complete, add to", ex: "Bitte ergänzen Sie den Satz.", exEn: "Please complete the sentence." },
  { inf: "ermitteln", pres: "ermittelt", pret: "ermittelte", perfekt: "hat ermittelt", en: "to investigate, determine", ex: "Die Polizei ermittelt den Täter.", exEn: "The police investigate the culprit." },
  { inf: "eröffnen", pres: "eröffnet", pret: "eröffnete", perfekt: "hat eröffnet", en: "to open (formally)", ex: "Die Bank eröffnet ein neues Konto.", exEn: "The bank opens a new account." },
  { inf: "erfüllen", pres: "erfüllt", pret: "erfüllte", perfekt: "hat erfüllt", en: "to fulfill", ex: "Er erfüllt seinen Traum.", exEn: "He fulfills his dream." },
  { inf: "ersetzen", pres: "ersetzt", pret: "ersetzte", perfekt: "hat ersetzt", en: "to replace", ex: "Wir ersetzen das alte Gerät.", exEn: "We replace the old device." },
  { inf: "erscheinen", pres: "erscheint", pret: "erschien", perfekt: "ist erschienen", en: "to appear, be published", ex: "Das Buch erscheint im Herbst.", exEn: "The book is published in autumn." },
  { inf: "erfahren", pres: "erfährt", pret: "erfuhr", perfekt: "hat erfahren", en: "to find out, experience", ex: "Ich erfahre die Neuigkeiten spät.", exEn: "I find out the news late." },
  { inf: "erhalten", pres: "erhält", pret: "erhielt", perfekt: "hat erhalten", en: "to receive, preserve", ex: "Sie erhält einen Brief.", exEn: "She receives a letter." },
  { inf: "erfinden", pres: "erfindet", pret: "erfand", perfekt: "hat erfunden", en: "to invent", ex: "Er erfindet eine neue Maschine.", exEn: "He invents a new machine." },
  { inf: "ernennen", pres: "ernennt", pret: "ernannte", perfekt: "hat ernannt", en: "to appoint", ex: "Man ernennt sie zur Direktorin.", exEn: "They appoint her director." },
  { inf: "verändern", pres: "verändert", pret: "veränderte", perfekt: "hat verändert", en: "to change", ex: "Die Zeit verändert alles.", exEn: "Time changes everything." },
  { inf: "verbessern", pres: "verbessert", pret: "verbesserte", perfekt: "hat verbessert", en: "to improve", ex: "Wir verbessern unsere Leistung.", exEn: "We improve our performance." },
  { inf: "verbinden", pres: "verbindet", pret: "verband", perfekt: "hat verbunden", en: "to connect, link", ex: "Diese Straße verbindet zwei Städte.", exEn: "This road connects two cities." },
  { inf: "verbringen", pres: "verbringt", pret: "verbrachte", perfekt: "hat verbracht", en: "to spend (time)", ex: "Wir verbringen den Urlaub am Meer.", exEn: "We spend the vacation at the sea." },
  { inf: "verdienen", pres: "verdient", pret: "verdiente", perfekt: "hat verdient", en: "to earn, deserve", ex: "Er verdient viel Geld.", exEn: "He earns a lot of money." },
  { inf: "vereinbaren", pres: "vereinbart", pret: "vereinbarte", perfekt: "hat vereinbart", en: "to agree on, arrange", ex: "Wir vereinbaren einen Termin.", exEn: "We arrange an appointment." },
  { inf: "verfolgen", pres: "verfolgt", pret: "verfolgte", perfekt: "hat verfolgt", en: "to pursue, follow", ex: "Die Polizei verfolgt den Dieb.", exEn: "The police pursue the thief." },
  { inf: "verfügen", pres: "verfügt", pret: "verfügte", perfekt: "hat verfügt", en: "to have at one's disposal", ex: "Er verfügt über viel Erfahrung.", exEn: "He has a lot of experience at his disposal." },
  { inf: "vergleichen", pres: "vergleicht", pret: "verglich", perfekt: "hat verglichen", en: "to compare", ex: "Man kann die zwei nicht vergleichen.", exEn: "One cannot compare the two." },
  { inf: "verhalten", pres: "verhält sich", pret: "verhielt sich", perfekt: "hat sich verhalten", en: "to behave (sich verhalten)", ex: "Er verhält sich merkwürdig.", exEn: "He behaves strangely." },
  { inf: "verhindern", pres: "verhindert", pret: "verhinderte", perfekt: "hat verhindert", en: "to prevent", ex: "Wir verhindern den Unfall.", exEn: "We prevent the accident." },
  { inf: "verkaufen", pres: "verkauft", pret: "verkaufte", perfekt: "hat verkauft", en: "to sell", ex: "Sie verkauft ihr Auto.", exEn: "She sells her car." },
  { inf: "verlangen", pres: "verlangt", pret: "verlangte", perfekt: "hat verlangt", en: "to demand", ex: "Der Chef verlangt mehr Einsatz.", exEn: "The boss demands more effort." },
  { inf: "verletzen", pres: "verletzt", pret: "verletzte", perfekt: "hat verletzt", en: "to injure, hurt", ex: "Er verletzt sich beim Sport.", exEn: "He injures himself during sports." },
  { inf: "vermeiden", pres: "vermeidet", pret: "vermied", perfekt: "hat vermieden", en: "to avoid", ex: "Wir vermeiden unnötigen Streit.", exEn: "We avoid unnecessary arguments." },
  { inf: "vermuten", pres: "vermutet", pret: "vermutete", perfekt: "hat vermutet", en: "to suspect, assume", ex: "Ich vermute, er hat recht.", exEn: "I assume he's right." },
  { inf: "verpassen", pres: "verpasst", pret: "verpasste", perfekt: "hat verpasst", en: "to miss (an opportunity)", ex: "Er verpasst den Zug.", exEn: "He misses the train." },
  { inf: "verschieben", pres: "verschiebt", pret: "verschob", perfekt: "hat verschoben", en: "to postpone, shift", ex: "Wir verschieben das Treffen.", exEn: "We postpone the meeting." },
  { inf: "verschwinden", pres: "verschwindet", pret: "verschwand", perfekt: "ist verschwunden", en: "to disappear", ex: "Das Geld verschwindet spurlos.", exEn: "The money disappears without a trace." },
  { inf: "versichern", pres: "versichert", pret: "versicherte", perfekt: "hat versichert", en: "to insure, assure", ex: "Ich versichere dir, es stimmt.", exEn: "I assure you, it's true." },
  { inf: "versprechen", pres: "verspricht", pret: "versprach", perfekt: "hat versprochen", en: "to promise", ex: "Er verspricht, pünktlich zu sein.", exEn: "He promises to be punctual." },
  { inf: "verstecken", pres: "versteckt", pret: "versteckte", perfekt: "hat versteckt", en: "to hide", ex: "Die Kinder verstecken sich im Garten.", exEn: "The children hide in the garden." },
  { inf: "verteidigen", pres: "verteidigt", pret: "verteidigte", perfekt: "hat verteidigt", en: "to defend", ex: "Der Anwalt verteidigt seinen Mandanten.", exEn: "The lawyer defends his client." },
  { inf: "vertrauen", pres: "vertraut", pret: "vertraute", perfekt: "hat vertraut", en: "to trust", ex: "Ich vertraue dir völlig.", exEn: "I trust you completely." },
  { inf: "verursachen", pres: "verursacht", pret: "verursachte", perfekt: "hat verursacht", en: "to cause", ex: "Der Sturm verursacht großen Schaden.", exEn: "The storm causes great damage." },
  { inf: "verwalten", pres: "verwaltet", pret: "verwaltete", perfekt: "hat verwaltet", en: "to manage, administer", ex: "Sie verwaltet das Budget.", exEn: "She manages the budget." },
  { inf: "verwenden", pres: "verwendet", pret: "verwendete", perfekt: "hat verwendet", en: "to use", ex: "Wir verwenden recyceltes Papier.", exEn: "We use recycled paper." },
  { inf: "verwirklichen", pres: "verwirklicht", pret: "verwirklichte", perfekt: "hat verwirklicht", en: "to realize, implement", ex: "Er verwirklicht seinen Traum.", exEn: "He realizes his dream." },
  { inf: "verzichten", pres: "verzichtet", pret: "verzichtete", perfekt: "hat verzichtet", en: "to do without, forgo", ex: "Sie verzichtet auf Süßigkeiten.", exEn: "She forgoes sweets." },
  { inf: "verlieben", pres: "verliebt sich", pret: "verliebte sich", perfekt: "hat sich verliebt", en: "to fall in love (sich verlieben)", ex: "Er verliebt sich sofort.", exEn: "He falls in love immediately." },
  { inf: "verschreiben", pres: "verschreibt", pret: "verschrieb", perfekt: "hat verschrieben", en: "to prescribe", ex: "Der Arzt verschreibt ein Medikament.", exEn: "The doctor prescribes a medication." },
  { inf: "beachten", pres: "beachtet", pret: "beachtete", perfekt: "hat beachtet", en: "to observe, note", ex: "Bitte beachten Sie die Regeln.", exEn: "Please observe the rules." },
  { inf: "beantworten", pres: "beantwortet", pret: "beantwortete", perfekt: "hat beantwortet", en: "to answer", ex: "Er beantwortet die Frage sofort.", exEn: "He answers the question immediately." },
  { inf: "bedanken", pres: "bedankt sich", pret: "bedankte sich", perfekt: "hat sich bedankt", en: "to thank (sich bedanken)", ex: "Ich bedanke mich für die Hilfe.", exEn: "I thank you for the help." },
  { inf: "bedeuten", pres: "bedeutet", pret: "bedeutete", perfekt: "hat bedeutet", en: "to mean", ex: "Was bedeutet dieses Wort?", exEn: "What does this word mean?" },
  { inf: "beeinflussen", pres: "beeinflusst", pret: "beeinflusste", perfekt: "hat beeinflusst", en: "to influence", ex: "Die Werbung beeinflusst die Kinder.", exEn: "Advertising influences children." },
  { inf: "beenden", pres: "beendet", pret: "beendete", perfekt: "hat beendet", en: "to finish, end", ex: "Sie beendet ihr Studium bald.", exEn: "She'll finish her studies soon." },
  { inf: "befinden", pres: "befindet sich", pret: "befand sich", perfekt: "hat sich befunden", en: "to be located (sich befinden)", ex: "Das Büro befindet sich im dritten Stock.", exEn: "The office is located on the third floor." },
  { inf: "befragen", pres: "befragt", pret: "befragte", perfekt: "hat befragt", en: "to question, survey", ex: "Man befragt hundert Personen.", exEn: "They survey a hundred people." },
  { inf: "begegnen", pres: "begegnet", pret: "begegnete", perfekt: "ist begegnet", en: "to encounter, meet", ex: "Ich begegne ihm oft im Park.", exEn: "I often meet him in the park." },
  { inf: "begeistern", pres: "begeistert", pret: "begeisterte", perfekt: "hat begeistert", en: "to enthuse, excite", ex: "Das Konzert begeistert das Publikum.", exEn: "The concert excites the audience." },
  { inf: "begleiten", pres: "begleitet", pret: "begleitete", perfekt: "hat begleitet", en: "to accompany", ex: "Er begleitet mich zum Arzt.", exEn: "He accompanies me to the doctor." },
  { inf: "begründen", pres: "begründet", pret: "begründete", perfekt: "hat begründet", en: "to justify", ex: "Sie begründet ihre Entscheidung.", exEn: "She justifies her decision." },
  { inf: "behalten", pres: "behält", pret: "behielt", perfekt: "hat behalten", en: "to keep", ex: "Ich behalte das Geheimnis für mich.", exEn: "I keep the secret to myself." },
  { inf: "behandeln", pres: "behandelt", pret: "behandelte", perfekt: "hat behandelt", en: "to treat, handle", ex: "Der Arzt behandelt den Patienten.", exEn: "The doctor treats the patient." },
  { inf: "beherrschen", pres: "beherrscht", pret: "beherrschte", perfekt: "hat beherrscht", en: "to master, control", ex: "Sie beherrscht drei Sprachen.", exEn: "She masters three languages." },
  { inf: "behindern", pres: "behindert", pret: "behinderte", perfekt: "hat behindert", en: "to hinder, obstruct", ex: "Der Stau behindert den Verkehr.", exEn: "The traffic jam obstructs the traffic." },
  { inf: "beitragen", pres: "trägt bei", pret: "trug bei", perfekt: "hat beigetragen", en: "to contribute", ex: "Jeder trägt zum Erfolg bei.", exEn: "Everyone contributes to the success." },
  { inf: "bekommen", pres: "bekommt", pret: "bekam", perfekt: "hat bekommen", en: "to get, receive", ex: "Sie bekommt ein Paket.", exEn: "She receives a package." },
  { inf: "belasten", pres: "belastet", pret: "belastete", perfekt: "hat belastet", en: "to burden", ex: "Die Arbeit belastet ihn sehr.", exEn: "The work burdens him greatly." },
  { inf: "beleidigen", pres: "beleidigt", pret: "beleidigte", perfekt: "hat beleidigt", en: "to insult", ex: "Er beleidigt niemanden absichtlich.", exEn: "He doesn't insult anyone on purpose." },
  { inf: "bemerken", pres: "bemerkt", pret: "bemerkte", perfekt: "hat bemerkt", en: "to notice", ex: "Ich bemerke den Unterschied sofort.", exEn: "I notice the difference immediately." },
  { inf: "bemühen", pres: "bemüht sich", pret: "bemühte sich", perfekt: "hat sich bemüht", en: "to make an effort (sich bemühen)", ex: "Er bemüht sich um gute Noten.", exEn: "He makes an effort for good grades." },
  { inf: "benutzen", pres: "benutzt", pret: "benutzte", perfekt: "hat benutzt", en: "to use", ex: "Wir benutzen öffentliche Verkehrsmittel.", exEn: "We use public transportation." },
  { inf: "beobachten", pres: "beobachtet", pret: "beobachtete", perfekt: "hat beobachtet", en: "to observe", ex: "Die Forscher beobachten die Tiere.", exEn: "The researchers observe the animals." },
  { inf: "beraten", pres: "berät", pret: "beriet", perfekt: "hat beraten", en: "to advise", ex: "Der Berater berät die Kunden.", exEn: "The advisor advises the customers." },
  { inf: "berechnen", pres: "berechnet", pret: "berechnete", perfekt: "hat berechnet", en: "to calculate", ex: "Sie berechnet die Kosten genau.", exEn: "She calculates the costs precisely." },
  { inf: "berichten", pres: "berichtet", pret: "berichtete", perfekt: "hat berichtet", en: "to report", ex: "Die Zeitung berichtet über den Unfall.", exEn: "The newspaper reports on the accident." },
  { inf: "berücksichtigen", pres: "berücksichtigt", pret: "berücksichtigte", perfekt: "hat berücksichtigt", en: "to take into account", ex: "Wir berücksichtigen Ihre Wünsche.", exEn: "We take your wishes into account." },
  { inf: "beschäftigen", pres: "beschäftigt sich", pret: "beschäftigte sich", perfekt: "hat sich beschäftigt", en: "to occupy oneself, deal with", ex: "Sie beschäftigt sich mit Kunst.", exEn: "She occupies herself with art." },
  { inf: "beschließen", pres: "beschließt", pret: "beschloss", perfekt: "hat beschlossen", en: "to decide, resolve", ex: "Wir beschließen, umzuziehen.", exEn: "We decide to move." },
  { inf: "beschreiben", pres: "beschreibt", pret: "beschrieb", perfekt: "hat beschrieben", en: "to describe", ex: "Beschreiben Sie das Bild.", exEn: "Describe the picture." },
  { inf: "beschweren", pres: "beschwert sich", pret: "beschwerte sich", perfekt: "hat sich beschwert", en: "to complain (sich beschweren)", ex: "Er beschwert sich über den Lärm.", exEn: "He complains about the noise." },
  { inf: "besichtigen", pres: "besichtigt", pret: "besichtigte", perfekt: "hat besichtigt", en: "to visit, view (sights)", ex: "Wir besichtigen das Schloss.", exEn: "We visit the castle." },
  { inf: "besitzen", pres: "besitzt", pret: "besaß", perfekt: "hat besessen", en: "to own, possess", ex: "Sie besitzt ein kleines Haus.", exEn: "She owns a small house." },
  { inf: "besorgen", pres: "besorgt", pret: "besorgte", perfekt: "hat besorgt", en: "to procure, get", ex: "Ich besorge die Getränke.", exEn: "I'll get the drinks." },
  { inf: "besprechen", pres: "bespricht", pret: "besprach", perfekt: "hat besprochen", en: "to discuss", ex: "Wir besprechen das Projekt.", exEn: "We discuss the project." },
  { inf: "bestellen", pres: "bestellt", pret: "bestellte", perfekt: "hat bestellt", en: "to order", ex: "Er bestellt eine Pizza.", exEn: "He orders a pizza." },
  { inf: "bestimmen", pres: "bestimmt", pret: "bestimmte", perfekt: "hat bestimmt", en: "to determine, decide", ex: "Du bestimmst die Regeln.", exEn: "You determine the rules." },
  { inf: "bestrafen", pres: "bestraft", pret: "bestrafte", perfekt: "hat bestraft", en: "to punish", ex: "Man bestraft den Betrug streng.", exEn: "They punish fraud severely." },
  { inf: "besuchen", pres: "besucht", pret: "besuchte", perfekt: "hat besucht", en: "to visit", ex: "Ich besuche meine Oma am Wochenende.", exEn: "I visit my grandma on the weekend." },
  { inf: "beteiligen", pres: "beteiligt sich", pret: "beteiligte sich", perfekt: "hat sich beteiligt", en: "to participate (sich beteiligen)", ex: "Viele beteiligen sich an der Aktion.", exEn: "Many participate in the campaign." },
  { inf: "betonen", pres: "betont", pret: "betonte", perfekt: "hat betont", en: "to emphasize", ex: "Sie betont die Wichtigkeit der Bildung.", exEn: "She emphasizes the importance of education." },
  { inf: "betrachten", pres: "betrachtet", pret: "betrachtete", perfekt: "hat betrachtet", en: "to look at, consider", ex: "Er betrachtet das Problem genau.", exEn: "He considers the problem closely." },
  { inf: "betreffen", pres: "betrifft", pret: "betraf", perfekt: "hat betroffen", en: "to concern, affect", ex: "Das betrifft uns alle.", exEn: "That concerns all of us." },
  { inf: "betreiben", pres: "betreibt", pret: "betrieb", perfekt: "hat betrieben", en: "to operate, run (a business)", ex: "Sie betreibt ein kleines Café.", exEn: "She runs a small café." },
  { inf: "betreuen", pres: "betreut", pret: "betreute", perfekt: "hat betreut", en: "to look after, supervise", ex: "Die Erzieherin betreut die Kinder.", exEn: "The caregiver looks after the children." },
  { inf: "beurteilen", pres: "beurteilt", pret: "beurteilte", perfekt: "hat beurteilt", en: "to judge, assess", ex: "Der Lehrer beurteilt die Arbeit fair.", exEn: "The teacher assesses the work fairly." },
  { inf: "bewahren", pres: "bewahrt", pret: "bewahrte", perfekt: "hat bewahrt", en: "to preserve, keep", ex: "Wir bewahren alte Traditionen.", exEn: "We preserve old traditions." },
  { inf: "beweisen", pres: "beweist", pret: "bewies", perfekt: "hat bewiesen", en: "to prove", ex: "Er beweist seine Unschuld.", exEn: "He proves his innocence." },
  { inf: "bewerben", pres: "bewirbt sich", pret: "bewarb sich", perfekt: "hat sich beworben", en: "to apply (for a job)", ex: "Sie bewirbt sich um die Stelle.", exEn: "She applies for the position." },
  { inf: "bewirken", pres: "bewirkt", pret: "bewirkte", perfekt: "hat bewirkt", en: "to cause, bring about", ex: "Die Medizin bewirkt eine schnelle Besserung.", exEn: "The medicine brings about a quick improvement." },
  { inf: "bezahlen", pres: "bezahlt", pret: "bezahlte", perfekt: "hat bezahlt", en: "to pay", ex: "Er bezahlt die Rechnung bar.", exEn: "He pays the bill in cash." },
  { inf: "beziehen", pres: "bezieht sich", pret: "bezog sich", perfekt: "hat sich bezogen", en: "to refer to (sich beziehen)", ex: "Das bezieht sich auf den letzten Absatz.", exEn: "That refers to the last paragraph." },
  { inf: "entdecken", pres: "entdeckt", pret: "entdeckte", perfekt: "hat entdeckt", en: "to discover", ex: "Forscher entdecken eine neue Art.", exEn: "Researchers discover a new species." },
  { inf: "entfernen", pres: "entfernt", pret: "entfernte", perfekt: "hat entfernt", en: "to remove", ex: "Sie entfernt den Fleck.", exEn: "She removes the stain." },
  { inf: "entscheiden", pres: "entscheidet", pret: "entschied", perfekt: "hat entschieden", en: "to decide", ex: "Wir entscheiden uns für die Reise.", exEn: "We decide on the trip." },
  { inf: "entschuldigen", pres: "entschuldigt sich", pret: "entschuldigte sich", perfekt: "hat sich entschuldigt", en: "to apologize (sich entschuldigen)", ex: "Er entschuldigt sich für die Verspätung.", exEn: "He apologizes for the delay." },
  { inf: "entspannen", pres: "entspannt sich", pret: "entspannte sich", perfekt: "hat sich entspannt", en: "to relax (sich entspannen)", ex: "Ich entspanne mich am Wochenende.", exEn: "I relax on the weekend." },
  { inf: "entsprechen", pres: "entspricht", pret: "entsprach", perfekt: "hat entsprochen", en: "to correspond to", ex: "Das entspricht nicht der Wahrheit.", exEn: "That does not correspond to the truth." },
  { inf: "entwerfen", pres: "entwirft", pret: "entwarf", perfekt: "hat entworfen", en: "to design, draft", ex: "Die Architektin entwirft ein Gebäude.", exEn: "The architect designs a building." },
  { inf: "entwickeln", pres: "entwickelt", pret: "entwickelte", perfekt: "hat entwickelt", en: "to develop", ex: "Die Firma entwickelt eine neue App.", exEn: "The company develops a new app." },
  { inf: "entziehen", pres: "entzieht", pret: "entzog", perfekt: "hat entzogen", en: "to withdraw, deprive", ex: "Man entzieht ihm den Führerschein.", exEn: "They revoke his driver's license." },
  { inf: "enttäuschen", pres: "enttäuscht", pret: "enttäuschte", perfekt: "hat enttäuscht", en: "to disappoint", ex: "Das Ergebnis enttäuscht die Fans.", exEn: "The result disappoints the fans." },

  // --- Everyday & -ieren verbs high-yield for B2 ---
  { inf: "funktionieren", pres: "funktioniert", pret: "funktionierte", perfekt: "hat funktioniert", en: "to function, work", ex: "Die Maschine funktioniert einwandfrei.", exEn: "The machine works perfectly." },
  { inf: "existieren", pres: "existiert", pret: "existierte", perfekt: "hat existiert", en: "to exist", ex: "Diese Tradition existiert seit Jahrhunderten.", exEn: "This tradition has existed for centuries." },
  { inf: "reagieren", pres: "reagiert", pret: "reagierte", perfekt: "hat reagiert", en: "to react", ex: "Er reagiert schnell auf Gefahr.", exEn: "He reacts quickly to danger." },
  { inf: "diskutieren", pres: "diskutiert", pret: "diskutierte", perfekt: "hat diskutiert", en: "to discuss", ex: "Wir diskutieren über Politik.", exEn: "We discuss politics." },
  { inf: "reduzieren", pres: "reduziert", pret: "reduzierte", perfekt: "hat reduziert", en: "to reduce", ex: "Die Firma reduziert die Kosten.", exEn: "The company reduces costs." },
  { inf: "kritisieren", pres: "kritisiert", pret: "kritisierte", perfekt: "hat kritisiert", en: "to criticize", ex: "Er kritisiert den Vorschlag.", exEn: "He criticizes the proposal." },
  { inf: "organisieren", pres: "organisiert", pret: "organisierte", perfekt: "hat organisiert", en: "to organize", ex: "Sie organisiert die Veranstaltung.", exEn: "She organizes the event." },
  { inf: "informieren", pres: "informiert", pret: "informierte", perfekt: "hat informiert", en: "to inform", ex: "Bitte informieren Sie uns rechtzeitig.", exEn: "Please inform us in time." },
  { inf: "präsentieren", pres: "präsentiert", pret: "präsentierte", perfekt: "hat präsentiert", en: "to present", ex: "Er präsentiert die Ergebnisse.", exEn: "He presents the results." },
  { inf: "konzentrieren", pres: "konzentriert sich", pret: "konzentrierte sich", perfekt: "hat sich konzentriert", en: "to concentrate (sich konzentrieren)", ex: "Ich konzentriere mich auf die Arbeit.", exEn: "I concentrate on the work." },
  { inf: "interessieren", pres: "interessiert sich", pret: "interessierte sich", perfekt: "hat sich interessiert", en: "to be interested (sich interessieren)", ex: "Sie interessiert sich für Musik.", exEn: "She is interested in music." },
  { inf: "freuen", pres: "freut sich", pret: "freute sich", perfekt: "hat sich gefreut", en: "to be happy (sich freuen)", ex: "Ich freue mich auf die Ferien.", exEn: "I'm looking forward to the holidays." },
  { inf: "wundern", pres: "wundert sich", pret: "wunderte sich", perfekt: "hat sich gewundert", en: "to be surprised (sich wundern)", ex: "Er wundert sich über das Ergebnis.", exEn: "He is surprised by the result." },
  { inf: "erinnern", pres: "erinnert sich", pret: "erinnerte sich", perfekt: "hat sich erinnert", en: "to remember (sich erinnern)", ex: "Ich erinnere mich an den Tag.", exEn: "I remember that day." },
  { inf: "handeln", pres: "handelt", pret: "handelte", perfekt: "hat gehandelt", en: "to act, trade", ex: "Wir müssen schnell handeln.", exEn: "We must act quickly." },
  { inf: "dienen", pres: "dient", pret: "diente", perfekt: "hat gedient", en: "to serve", ex: "Das dient einem guten Zweck.", exEn: "That serves a good purpose." },
  { inf: "folgen", pres: "folgt", pret: "folgte", perfekt: "ist gefolgt", en: "to follow", ex: "Der Hund folgt seinem Besitzer.", exEn: "The dog follows its owner." },
  { inf: "gehören", pres: "gehört", pret: "gehörte", perfekt: "hat gehört", en: "to belong", ex: "Das Buch gehört mir.", exEn: "The book belongs to me." },
  { inf: "leiten", pres: "leitet", pret: "leitete", perfekt: "hat geleitet", en: "to lead, manage", ex: "Sie leitet die Abteilung.", exEn: "She leads the department." },
  { inf: "leisten", pres: "leistet", pret: "leistete", perfekt: "hat geleistet", en: "to accomplish, afford", ex: "Wir können uns das leisten.", exEn: "We can afford that." },
  { inf: "liefern", pres: "liefert", pret: "lieferte", perfekt: "hat geliefert", en: "to deliver", ex: "Die Firma liefert die Ware pünktlich.", exEn: "The company delivers the goods on time." },
  { inf: "planen", pres: "plant", pret: "plante", perfekt: "hat geplant", en: "to plan", ex: "Wir planen eine Reise.", exEn: "We're planning a trip." },
  { inf: "prüfen", pres: "prüft", pret: "prüfte", perfekt: "hat geprüft", en: "to test, check", ex: "Der Lehrer prüft die Aufgaben.", exEn: "The teacher checks the assignments." },
  { inf: "wechseln", pres: "wechselt", pret: "wechselte", perfekt: "hat gewechselt", en: "to change, switch", ex: "Er wechselt den Job.", exEn: "He changes jobs." },
  { inf: "zweifeln", pres: "zweifelt", pret: "zweifelte", perfekt: "hat gezweifelt", en: "to doubt", ex: "Ich zweifle nicht an dir.", exEn: "I don't doubt you." },
  { inf: "arbeiten", pres: "arbeitet", pret: "arbeitete", perfekt: "hat gearbeitet", en: "to work", ex: "Er arbeitet in einem Büro.", exEn: "He works in an office." },
  { inf: "wohnen", pres: "wohnt", pret: "wohnte", perfekt: "hat gewohnt", en: "to live, reside", ex: "Sie wohnt in München.", exEn: "She lives in Munich." },
  { inf: "spielen", pres: "spielt", pret: "spielte", perfekt: "hat gespielt", en: "to play", ex: "Die Kinder spielen im Garten.", exEn: "The children play in the garden." },
  { inf: "lernen", pres: "lernt", pret: "lernte", perfekt: "hat gelernt", en: "to learn", ex: "Ich lerne jeden Tag Deutsch.", exEn: "I learn German every day." },
  { inf: "kaufen", pres: "kauft", pret: "kaufte", perfekt: "hat gekauft", en: "to buy", ex: "Wir kaufen frisches Gemüse.", exEn: "We buy fresh vegetables." },
  { inf: "brauchen", pres: "braucht", pret: "brauchte", perfekt: "hat gebraucht", en: "to need", ex: "Ich brauche mehr Zeit.", exEn: "I need more time." },
  { inf: "glauben", pres: "glaubt", pret: "glaubte", perfekt: "hat geglaubt", en: "to believe", ex: "Sie glaubt an sich selbst.", exEn: "She believes in herself." },
  { inf: "sagen", pres: "sagt", pret: "sagte", perfekt: "hat gesagt", en: "to say", ex: "Er sagt immer die Wahrheit.", exEn: "He always tells the truth." },
  { inf: "machen", pres: "macht", pret: "machte", perfekt: "hat gemacht", en: "to make, do", ex: "Was machst du am Wochenende?", exEn: "What are you doing on the weekend?" },
  { inf: "leben", pres: "lebt", pret: "lebte", perfekt: "hat gelebt", en: "to live", ex: "Wir leben in einer kleinen Stadt.", exEn: "We live in a small town." },
  { inf: "hoffen", pres: "hofft", pret: "hoffte", perfekt: "hat gehofft", en: "to hope", ex: "Ich hoffe auf gutes Wetter.", exEn: "I hope for good weather." },
  { inf: "zeigen", pres: "zeigt", pret: "zeigte", perfekt: "hat gezeigt", en: "to show", ex: "Er zeigt mir den Weg.", exEn: "He shows me the way." },
  { inf: "nutzen", pres: "nutzt", pret: "nutzte", perfekt: "hat genutzt", en: "to use, utilize", ex: "Wir nutzen die Chance.", exEn: "We seize the opportunity." },
  { inf: "wirken", pres: "wirkt", pret: "wirkte", perfekt: "hat gewirkt", en: "to have an effect, seem", ex: "Das Medikament wirkt schnell.", exEn: "The medication works quickly." },
];
